
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Bash@3
  displayName: 'Install Inspec'
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here

      echo '** Download Inspec 4.12.0'

      curl https://packages.chef.io/files/stable/inspec/4.12.0/ubuntu/16.04/inspec_4.12.0-1_amd64.deb -o inspec.deb

      echo '** Running dpkg to install Inspec'
      sudo dpkg -i inspec.deb

      echo '** Accepting License'
      inspec --chef-license=accept 

- task: Bash@3
  displayName: 'Run inspec and generate results'
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      inspec exec hello_spec.rb --reporter cli junit:testresults.xml html:report.html

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/testresults.xml'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'report.html'
    ArtifactName: 'report'