
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

- task: Bash@3
  displayName: 'Install Inspec'
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here

      echo '** Download Inspec 4.12.0'

      curl https://packages.chef.io/files/stable/inspec/4.12.0/ubuntu/16.04/inspec_4.12.0-1_amd64.deb -o inspec.deb

      echo '** Running dpkg to install Inspec'
      sudo dpkg -i inspec.deb

      echo '** Accepting License'
      inspec --chef-license=accept 

